"""Tests for MoveIt endpoint goals generated by piper_move_x."""

import pytest

from piper.piper_move_x import PiperMoveX


def moveit_goal(enable_motion):
    """Build a goal without constructing a live ROS node."""
    node = object.__new__(PiperMoveX)
    node.target_tcp = (0.42, -0.03, 0.54)
    node.target_tcp_quaternion = (0.0, 0.70710678, 0.0, 0.70710678)
    node.enable_motion = enable_motion
    return node._moveit_goal()


def ownership_node(position_publishers, joint_publishers):
    """Create a node shell returning controlled publisher counts."""
    node = object.__new__(PiperMoveX)
    counts = {
        '/pos_cmd': position_publishers,
        '/joint_ctrl_single': joint_publishers,
    }
    node.count_publishers = counts.__getitem__
    return node


@pytest.mark.parametrize(
    'enable_motion, plan_only',
    [(False, True), (True, False)],
)
def test_enable_motion_selects_plan_only(enable_motion, plan_only):
    """Dry-run and real execution map to MoveGroup planning options."""
    goal = moveit_goal(enable_motion)

    assert goal.planning_options.plan_only is plan_only
    assert goal.planning_options.replan is enable_motion


def test_goal_preserves_tcp_endpoint_and_orientation():
    """The MoveIt constraint contains the requested base-frame TCP pose."""
    goal = moveit_goal(True)
    constraints = goal.request.goal_constraints[0]
    position_constraint = constraints.position_constraints[0]
    orientation_constraint = constraints.orientation_constraints[0]
    pose = position_constraint.constraint_region.primitive_poses[0]

    assert goal.request.group_name == 'arm'
    assert position_constraint.header.frame_id == 'base_link'
    assert position_constraint.link_name == 'tcp_link'
    assert (pose.position.x, pose.position.y, pose.position.z) == (
        0.42,
        -0.03,
        0.54,
    )
    assert orientation_constraint.orientation == pose.orientation


def test_goal_uses_configured_moveit_tolerances():
    """Position and orientation constraints retain guarded tolerances."""
    goal = moveit_goal(True)
    constraints = goal.request.goal_constraints[0]
    region = constraints.position_constraints[0].constraint_region
    orientation = constraints.orientation_constraints[0]

    assert region.primitives[0].dimensions == pytest.approx(
        [0.004, 0.004, 0.004]
    )
    assert orientation.absolute_x_axis_tolerance == pytest.approx(0.05)
    assert orientation.absolute_y_axis_tolerance == pytest.approx(0.05)
    assert orientation.absolute_z_axis_tolerance == pytest.approx(0.05)


def test_cartesian_ownership_requires_exclusive_direct_publisher():
    """Direct interpolation allows itself and no joint command source."""
    node = ownership_node(1, 0)

    node._check_cartesian_ownership()

    with pytest.raises(RuntimeError):
        ownership_node(2, 0)._check_cartesian_ownership()
    with pytest.raises(RuntimeError):
        ownership_node(1, 1)._check_cartesian_ownership()


def test_moveit_ownership_requires_trajectory_bridge_only():
    """MoveIt requires one joint bridge and no direct pose publisher."""
    node = ownership_node(0, 1)

    node._check_moveit_ownership()

    with pytest.raises(RuntimeError):
        ownership_node(1, 1)._check_moveit_ownership()
    with pytest.raises(RuntimeError):
        ownership_node(0, 0)._check_moveit_ownership()
