<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>piper_pbvs_control</name>
  <version>0.1.0</version>
  <description>Vision-guided MoveIt coarse positioning for Piper.</description>
  <maintainer email="xie@todo.todo">xie</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>action_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>shape_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>piper_msgs</depend>
  <exec_depend>piper_vision</exec_depend>
  <exec_depend>piper_tf</exec_depend>
  <exec_depend>piper_with_gripper_moveit</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>trajectory_msgs</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
